# Generated by Django 5.1.7 on 2025-04-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='sport',
            field=models.CharField(blank=True, choices=[('football', 'Football'), ('cricket', 'Cricket'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('badminton', 'Badminton')], max_length=20, null=True),
        ),
    ]
