# Generated by Django 5.1.7 on 2025-04-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_turf_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='turf',
            name='sport',
        ),
        migrations.AddField(
            model_name='turf',
            name='sport_prices',
            field=models.JSONField(blank=True, default=dict, help_text={'description': 'Store sport-specific prices. Format: {"sport_id": price_per_hr}'}),
        ),
        migrations.AddField(
            model_name='turf',
            name='sports',
            field=models.ManyToManyField(related_name='turfs', to='host.sport'),
        ),
    ]
