# Generated by Django 5.1.7 on 2025-04-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_sport_remove_turf_sport_turf_sport_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='sport_prices',
        ),
    ]
