# Generated by Django 5.1.7 on 2025-04-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_remove_turf_sport_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_offline',
            field=models.BooleanField(default=False),
        ),
    ]
