# Generated by Django 5.2 on 2025-04-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_booking_is_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
